### PR TITLE
bug(types): SwipeableHandlers.ref accepts null.

### LINKED ISSUE #140: Typescript error when using useSwipable hook and applying handlers.
Using the hook, I have typed the handlers as SwipeableHandlers and spread them on to the swipeable div. However this results in a Typescript error.  Any help would be most appreciated.  Thanks

Error

```
Type '{ children: Element[]; ref: ({}: HTMLElement) => void; onMouseDown?: ((event: MouseEvent<Element, MouseEvent>) => void) | undefined; className: string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Type '{ children: Element[]; ref: ({}: HTMLElement) => void; onMouseDown?: ((event: MouseEvent<Element, MouseEvent>) => void) | undefined; className: string; }' is not assignable to type 'ClassAttributes<HTMLDivElement>'.
    Types of property 'ref' are incompatible.
      Type '({}: HTMLElement) => void' is not assignable to type 'string | ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined'.
        Type '({}: HTMLElement) => void' is not assignable to type '(instance: HTMLDivElement | null) => void'.
          Types of parameters '__0' and 'instance' are incompatible.
            Type 'HTMLDivElement | null' is not assignable to type 'HTMLElement'.
              Type 'null' is not assignable to type 'HTMLElement'.ts(2322)
```

Code

```
    const handlers: SwipeableHandlers = useSwipeable({
        onSwipedLeft: handleOnSwipedLeft,
        onSwipedRight: handleOnSwipedRight,
        onSwiped: handleOnSwiped,
        onSwiping: handleSwiping,
        delta: horizontalSwipeThreshold,
        preventDefaultTouchmoveEvent: true,
        trackTouch: true,
    });

    return (
        <div {...handlers}>
           ...
        </div>
    );
```

### PR DESCRIPTION
**Pull request by mastermatt**
Fixes #140.

Adds test to explicitly cover this case because it seems `dtslint`
doesn't catch the issue when a handlers instance is spread during an
`Element` instantiation. The React types do [declare the arg correctly](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L85).

### CODE REVIEW

File: types/index.d.ts [hunk 1]
```diff
@@ -34,14 +34,14 @@ export interface SwipeableOptions {
 // Component Specific Props
 export interface SwipeableProps {
   nodeName?: string
-  innerRef?: ({}: HTMLElement) => void
+  innerRef?: (element: HTMLElement) => void
```
Comment (hartzis) [inline types/index.d.ts]: this should probably also be `(element: HTMLElement | null) => void` as it also just forwards the regular `ref` call: https://github.com/dogfessional/react-swipeable/blob/master/src/index.js#L227

File: types/test.tsx [hunk 2]
```diff
@@ -56,3 +56,14 @@ const TestHook = () => {
...
+const handlers: SwipeableHandlers = useSwipeable({
+  onSwipedLeft: (data) => {
+    data // $ExpectType EventData
+  },
+  preventDefaultTouchmoveEvent: true,
+  trackTouch: true,
+})
+
+handlers.ref(<div />)
+handlers.ref(null)
```
Comment (hartzis) [inline types/test.tsx]: awesome tests! thank you!

File: types/index.d.ts (hunk 1 above)
Comment (mastermatt) [reply types/index.d.ts]: I added this too, but I have no idea how to write a test that uses this function 🤷‍♂
